2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_setup.py:_flush():76] Configure stats pid to 34600
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_setup.py:_flush():76] Loading settings from /Users/paul/.config/wandb/settings
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_setup.py:_flush():76] Loading settings from /Users/paul/Projects/anomalous-concept-detection/wandb/settings
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_init.py:_log_setup():521] Logging user logs to /Users/paul/Projects/anomalous-concept-detection/wandb/run-20240502_160358-0agk5tl5/logs/debug.log
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/paul/Projects/anomalous-concept-detection/wandb/run-20240502_160358-0agk5tl5/logs/debug-internal.log
2024-05-02 16:03:58,042 INFO    MainThread:34600 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x2a1694a90>
2024-05-02 16:03:58,043 INFO    MainThread:34600 [wandb_init.py:init():561] calling init triggers
2024-05-02 16:03:58,043 INFO    MainThread:34600 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-05-02 16:03:58,043 INFO    MainThread:34600 [wandb_init.py:init():586] re-initializing run, found existing run on stack: i8mdzawr
2024-05-02 16:03:58,047 INFO    MainThread:34600 [wandb_run.py:_finish():2064] finishing run paul-colognese/Exploring direction detector/i8mdzawr
2024-05-02 16:03:58,047 INFO    MainThread:34600 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-05-02 16:03:58,049 INFO    MainThread:34600 [wandb_run.py:_restore():2287] restore
2024-05-02 16:03:58,049 INFO    MainThread:34600 [wandb_run.py:_restore():2293] restore done
2024-05-02 16:04:01,789 INFO    MainThread:34600 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-05-02 16:04:01,792 INFO    MainThread:34600 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-05-02 16:04:01,801 INFO    MainThread:34600 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-05-02 16:04:01,843 INFO    MainThread:34600 [wandb_init.py:init():611] starting backend
2024-05-02 16:04:01,843 INFO    MainThread:34600 [wandb_init.py:init():615] setting up manager
2024-05-02 16:04:01,854 INFO    MainThread:34600 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-02 16:04:01,855 INFO    MainThread:34600 [wandb_init.py:init():623] backend started and connected
2024-05-02 16:04:01,885 INFO    MainThread:34600 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-05-02 16:04:01,886 INFO    MainThread:34600 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-02 16:04:01,886 INFO    MainThread:34600 [wandb_init.py:init():715] updated telemetry
2024-05-02 16:04:02,080 INFO    MainThread:34600 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-02 16:04:03,175 INFO    MainThread:34600 [wandb_run.py:_on_init():2357] communicating current version
2024-05-02 16:04:03,289 INFO    MainThread:34600 [wandb_run.py:_on_init():2366] got version response 
2024-05-02 16:04:03,289 INFO    MainThread:34600 [wandb_init.py:init():799] starting run threads in backend
2024-05-02 16:04:05,239 INFO    MainThread:34600 [wandb_run.py:_console_start():2335] atexit reg
2024-05-02 16:04:05,239 INFO    MainThread:34600 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-05-02 16:04:05,239 INFO    MainThread:34600 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-05-02 16:04:05,240 INFO    MainThread:34600 [wandb_run.py:_redirect():2280] Redirects installed.
2024-05-02 16:04:05,241 INFO    MainThread:34600 [wandb_init.py:init():842] run started, returning control to user process
2024-05-02 16:04:07,467 INFO    MainThread:34600 [wandb_config.py:__setitem__():151] config set batch_size = 128 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x29f353f10>>
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_run.py:_config_callback():1347] config_cb batch_size 128 None
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_config.py:__setitem__():151] config set max_length = None - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x29f353f10>>
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_run.py:_config_callback():1347] config_cb max_length None None
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_config.py:__setitem__():151] config set num_test_samples = 16 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x29f353f10>>
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_run.py:_config_callback():1347] config_cb num_test_samples 16 None
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_config.py:__setitem__():151] config set num_detector_samples = 16 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x29f353f10>>
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_run.py:_config_callback():1347] config_cb num_detector_samples 16 None
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_config.py:__setitem__():151] config set model_name = openai-community/gpt2 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x29f353f10>>
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_run.py:_config_callback():1347] config_cb model_name openai-community/gpt2 None
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_config.py:__setitem__():151] config set dataset_size = 16 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x29f353f10>>
2024-05-02 16:04:07,468 INFO    MainThread:34600 [wandb_run.py:_config_callback():1347] config_cb dataset_size 16 None
2024-05-02 16:04:09,269 INFO    MainThread:34600 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-02 16:04:09,269 INFO    MainThread:34600 [wandb_init.py:_pause_backend():432] pausing backend
